### ISSUE TITLE
How do I compile "make" 

### ISSUE THREAD

**Issue by dtruong8** [felipemoura/RegularExpression-to-NFA-to-DFA#3]

**Comment by ahed-rashaida** [comment]
yes, Please!
How do I compile "make"?
becouse your project doesn't run with me

**Comment by felipemoura** [comment]
Just hit "make" on your terminal
some resources for your:

- [Make install](https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install)
- [Tutorial makefile](http://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/)
